# Generated by Django 5.0.7 on 2025-05-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbontracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_user_vehicle",
            field=models.BooleanField(default=False),
        ),
    ]
