# Generated by Django 5.0.7 on 2025-05-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbontracker", "0002_car_is_user_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="end_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="end_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="start_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="start_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
