# Generated by Django 5.0.7 on 2025-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbontracker", "0003_route_end_lat_route_end_lng_route_start_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="maintenance_status",
            field=models.CharField(
                choices=[("good", "Good"), ("average", "Average"), ("poor", "Poor")],
                default="good",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="driving_conditions",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("heavy_traffic", "Heavy Traffic"),
                    ("off_road", "Off Road"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="maintenance_status",
            field=models.CharField(
                choices=[("good", "Good"), ("average", "Average"), ("poor", "Poor")],
                default="good",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="trans_mode",
            field=models.CharField(
                choices=[("car", "Car")], default="car", max_length=20
            ),
        ),
    ]
