# Generated by Django 5.0.7 on 2025-06-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "carbontracker",
            "0004_car_maintenance_status_journey_driving_conditions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="maintenance_status",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="maintenance_status",
        ),
    ]
