# Generated by Django 5.0.7 on 2025-06-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbontracker", "0005_remove_car_maintenance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="end_area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="end_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="end_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="start_area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="start_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="start_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
