# Generated by Django 5.0.7 on 2025-06-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "carbontracker",
            "0006_route_end_area_route_end_city_route_end_state_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="utility",
            old_name="bill_amount",
            new_name="units",
        ),
    ]
